version: "3"

services:
  node:
    build: .
    container_name: store_manager
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      PORT: '3000'

  db:
    container_name: store_manager_db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "StoreManager"
      MYSQL_ROOT_PASSWORD: 'password'
      hostname: store_manager_db
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/dump:/docker-entrypoint-initdb.d
    restart: always

networks:
  default:
    name: store_manager_net

volumes:
  node_modules:
